# Generated by Django 4.0.1 on 2022-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=40)),
                ('title_2', models.CharField(max_length=40)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
