# Generated by Django 3.2.9 on 2022-01-07 14:56

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('icon', models.ImageField(upload_to=base_app.models.Service.get_file_name)),
                ('timer', models.FloatField(default=0.2)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
