# Generated by Django 3.2.9 on 2022-01-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_booktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/chef')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.TextField(max_length=60)),
                ('link_1', models.CharField(max_length=100)),
                ('link_2', models.CharField(max_length=100)),
                ('link_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=150)),
                ('photo', models.ImageField(upload_to='images/feedback')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
