# Generated by Django 3.2.9 on 2022-01-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_chef_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='link_1',
            new_name='link_facebook',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='link_2',
            new_name='link_instagram',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='link_3',
            new_name='link_twitter',
        ),
    ]
